---
functional:
  - Пользователь должен иметь возможность зарегистрироваться с помощью учётной записи GITHAB или DISCORT.
  - Пользователь должен иметь возможность востанавливать акаунт в случае потери пароля.
  - Пользователь должен иметь возможность создавать игру с ботом, другом или случайным играком. 
  - Пользователь должен иметь возможность выбирать уровень сложности в игре, время игры, тип игры закрытый или открытый.
  - Пользователь должен иметь возможность сменя языка с англиского на русский и с русского на англиский.
  - Пользователь должен иметь возможность общаться в чате.
  - Встроенная система автомодерации в чате для автоудаления рекламы, ненормативной лексики, и призывам к сомнительным действиям.
  - Пользователь должен иметь возможность ввести код и провеверить его во время игры.
  - Пользователь должен иметь возможность писать сопернику в чате во время игры.
  - В случае победы или проигрыша должен вспылавть банер с оповещение о победе или проигрыше.
  - При первом начале игры для пользователя должна быть показана инструкция и правила.
  - Пользователь должен иметь возможность смотреть рейтинги играков.
  - Пользователь должен иметь возможность отказаться от приглашения в игру.
  - Пользователь должен иметь возможность видеть сколько пользователей в онлайн.
  - Пользователь должен иметь возможность выбирать играть на рейтинг или без рейтинга.
  - Пользователь должен иметь возможность писать личные соообщения.
  - Пользователь должен иметь возможность отменить своё приглашение. 
  - Пользователь должен иметь возможность филитровать данные рейтинга играков по времени (за неделю, за месяц и за всё время).

non-functional:
  - Сайт должен быть оптимизирован для мобильных устройств. 
  - Сайт должен защищать личные данные пользователя.
  - Сайт должен уыедомлять пользователя о брошенном вызове от другого пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен показывать рейтиг пользователей иргры.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
  - Сайт должен иметь совместимость со всеми операционными системами.
  - Сайт должен показывать текущую версию игры.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы

implicit: 
  - Пользователь должен иметь возможность регистрации с помощью мобильного телефона. 
  - Сайт должен уведомлять о хранение куки.
  - Сайт должен иметь функцию смены на ночную тему.
  - При регистрации сайт должен проверить пользователя и убедится, что он не бот.
  - Сайт должени иметь мобильное приложение.
  - Игра должана иметь установочный пакет для пк.
  - Пользователь должен иметь возможность загрузить свой аватар на сайте.
  - Возможность загружать картинки в чат, (чтобы перекинутся мемами с пользователями XD).
