---
functional:
- Пользователь должен иметь возможность зарегистрироваться с помощью учётной записи GITHAB или DISCORT.
- Пользователь должен иметь возможность востанавливать акаунт в случае потери пароля.
- Пользователь должен иметь возможность создавать игру с ботом, другом или случайным играком. 
- Пользователь должен иметь возможность выбирать уровень сложности в игре, время игры, тип игры закрытый или открытый.
- Пользователь должен иметь возможность сменя языка с англиского на русский и с русского на англиский.
- Пользователь должен иметь возможность общаться в чате.
- Встроенная система автомодерации в чате для автоудаления рекламы, ненормативной лексики, и призывам к сомнительным действиям.
- Пользователь должен иметь возможность ввести код и провеверить его во время игры.
- Пользователь должен иметь возможность писать сопернику в чате во время игры.
- В случае победы или проигрыша должен вспылавть банер с оповещение о победе или проигрыше.
- При первом начале игры для пользователя должна быть показана инструкция и правила.
- Пользователь должен иметь возможность смотреть рейтинги играков.
- Пользователь должен иметь возможность отказаться от приглашения в игру.
- Пользователь должен иметь возможность видеть сколько пользователей в онлайн.
- Пользователь должен иметь возможность выбирать играть на рейтинг или без рейтинга.
